// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface CertificateRegistry$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "CertificateRegistry";
  readonly sourceName: "contracts/CertificateRegistry.sol";
  readonly abi: [{"anonymous":false,"inputs":[{"indexed":true,"internalType":"bytes32","name":"certHash","type":"bytes32"},{"indexed":false,"internalType":"uint256","name":"timestamp","type":"uint256"},{"indexed":true,"internalType":"address","name":"registrar","type":"address"}],"name":"CertificateRegistered","type":"event"},{"inputs":[{"internalType":"bytes32","name":"","type":"bytes32"}],"name":"certificateTimestamps","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"bytes32","name":"certHash","type":"bytes32"}],"name":"isRegistered","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"bytes32","name":"certHash","type":"bytes32"}],"name":"registerCertificate","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"bytes32","name":"certHash","type":"bytes32"}],"name":"verifyCertificate","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x6080604052348015600e575f5ffd5b506101dc8061001c5f395ff3fe608060405234801561000f575f5ffd5b506004361061004a575f3560e01c806327258b221461004e57806360fdfcad14610084578063850c1768146100b1578063f101dce8146100d0575b5f5ffd5b61006f61005c36600461018f565b5f90815260208190526040902054151590565b60405190151581526020015b60405180910390f35b6100a361009236600461018f565b5f6020819052908152604090205481565b60405190815260200161007b565b6100a36100bf36600461018f565b5f9081526020819052604090205490565b6100e36100de36600461018f565b6100e5565b005b5f81815260208190526040902054156101445760405162461bcd60e51b815260206004820152601e60248201527f436572746966696361746520616c726561647920726567697374657265640000604482015260640160405180910390fd5b5f818152602081815260409182902042908190559151918252339183917fa26bffe1d0be2a3471c202f22603c75f871205392082fe3b3f1c2a9eeaba5e24910160405180910390a350565b5f6020828403121561019f575f5ffd5b503591905056fea2646970667358221220e627649050b1382194279f9be8905019df8f311e4f89ffb9647fef69a27eda5e64736f6c634300081c0033";
  readonly deployedBytecode: "0x608060405234801561000f575f5ffd5b506004361061004a575f3560e01c806327258b221461004e57806360fdfcad14610084578063850c1768146100b1578063f101dce8146100d0575b5f5ffd5b61006f61005c36600461018f565b5f90815260208190526040902054151590565b60405190151581526020015b60405180910390f35b6100a361009236600461018f565b5f6020819052908152604090205481565b60405190815260200161007b565b6100a36100bf36600461018f565b5f9081526020819052604090205490565b6100e36100de36600461018f565b6100e5565b005b5f81815260208190526040902054156101445760405162461bcd60e51b815260206004820152601e60248201527f436572746966696361746520616c726561647920726567697374657265640000604482015260640160405180910390fd5b5f818152602081815260409182902042908190559151918252339183917fa26bffe1d0be2a3471c202f22603c75f871205392082fe3b3f1c2a9eeaba5e24910160405180910390a350565b5f6020828403121561019f575f5ffd5b503591905056fea2646970667358221220e627649050b1382194279f9be8905019df8f311e4f89ffb9647fef69a27eda5e64736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/CertificateRegistry.sol";
  readonly buildInfoId: "solc-0_8_28-329061b986f1f3d2fb582b97f05e799941bd9e65";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["CertificateRegistry"]: CertificateRegistry$Type;
    ["contracts/CertificateRegistry.sol:CertificateRegistry"]: CertificateRegistry$Type;
  }
}